apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logging
spec:
  selector:
    matchLabels:
      app: httpd-logging
  template:
    metadata:
      labels:
        app: httpd-logging
    spec:
      containers:
        - name: webserver
          image: httpd
          ports:
            - containerPort: 80




apiVersion : app/v1
kind: DaemonSet
metadata:
   name: harish-daemonpods
spec:
    selector:
      matchLabels:
         app:harish
    template:     
          metadata:
              labels:
                  app:harish
          spec:        
             containers:
                -name: nginx
                 image: nginx



apiVersion : v1
kind : Pod
metadata: 
  name: static-pod
spec:
  containers:
     - name: static-pod
       image : nginx
       command:
         - sleep
         - '3600'


apiVersion: v1
kind: Pod
metadata:
  name: stat-pod
spec:
  containers:
      - name: stat-pods
        image: ubuntu
        command:
            - sleep
            - '3600'




